### ISSUE TITLE
Debug Japanese Classroom scene

### ISSUE THREAD

**Issue by wahn** [wahn/rs_pbrt#36]
The **C++** version does render the **Japanese Classroom** scene (from [https://benedikt-bitterli.me/resources](https://benedikt-bitterli.me/resources)) **fine**:

![classroom](https://user-images.githubusercontent.com/1074865/34609325-2b62d642-f214-11e7-86ca-32130c5155da.png)

Whereas the current **Rust** version **panics**:

```shell
> ./target/release/examples/pest_test -i ../../../../Downloads/classroom/scene.pbrt
FILE = ../../../../Downloads/classroom/scene.pbrt
search_directory is /home/jan/git/self_hosted/Rust/pbrt/../../../../Downloads/classroom
13596 bytes read
...
Rendering with 4 thread(s) ...
block_queue.len() = 3726
thread '<unnamed>' panicked at 'ld = RGBSpectrum { c: [-0.008398388, -0.010858062, -0.013359588] }', src/integrators/path.rs:128:29
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'ld = RGBSpectrum { c: [-12.454978, -12.454978, -12.454978] }', src/integrators/path.rs:128:29
1 / 3726 [>--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0.03 % 43633.82/s 0s 
thread '<unnamed>' panicked at 'ld = RGBSpectrum { c: [-11.307451, -11.307451, -11.307451] }', src/integrators/path.rs:128:29
thread '<unnamed>' panicked at 'ld = RGBSpectrum { c: [-19.646214, -19.646214, -19.646214] }', src/integrators/path.rs:128:29
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /checkout/src/libcore/result.rs:916:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /checkout/src/libcore/result.rs:916:5

```

**Comment by wahn** [comment]
It looks like `FresnelBlend::schlick_fresnel(...)` returns sometimes colors (`Spectrum`) with negative values.

**Comment by wahn** [comment]
After removing all `SubstrateMaterial` materials (and the geometry using it) we can render with the Rust version:

![pbrt](https://user-images.githubusercontent.com/1074865/34693642-64163bc8-f4bc-11e7-83a3-ab998584c67d.png)

So the problem might be missing implementations for transformations encapsulated via `TransformBegin` and `TransformEnd`:

```shell
> rg Transform ../../../../Downloads/classroom/scene.pbrt
2:Transform [ 0.988479 -0.00428443 0.151294 -0 -0 0.999599 0.0283071 -0 0.151355 0.027981 -0.988083 -0 0.780055 -1.44302 6.03615 1]
82:	TransformBegin
83:		Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 -0.0734223 0 1]
85:	TransformEnd
122:	TransformBegin
123:		Transform [ 11.6517 0 0 0 0 11.6517 0 0 0 0 11.6517 0 0 0 0 1]
125:	TransformEnd
201:	TransformBegin
202:		Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 -0.0734223 0 1]
204:	TransformEnd
206:	TransformBegin
207:		Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 -0.0734223 0 1]
209:	TransformEnd
211:	TransformBegin
212:		Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 -0.0734223 0 1]
214:	TransformEnd
216:	TransformBegin
217:		Transform [ -1 0 8.74228e-008 0 -8.74228e-008 0 -1 0 0 1 0 0 0 0 0 1]
219:	TransformEnd
```

**Comment by wahn** [comment]
Since commit 05fb6c4090d5918c37ac8fa6e444684dff865fd5 all problems regarding rendering the **Japanese Classroom** scene should be solved:

![pbrt](https://user-images.githubusercontent.com/1074865/34718944-8a7cd7bc-f530-11e7-9fc7-5c6b55ee94db.png)

There is a **difference** between the C++ and Rust version though:

![diff](https://user-images.githubusercontent.com/1074865/34719697-9ecaca8c-f533-11e7-8a61-bf93380f13ef.jpg)

```shell
> imf_diff -d -f classroom.png pbrt.png 
differing pixels:	 45.988% (423830 of 921600)
average difference:	  2.608%
maximum difference:	 54.947%
Summary: Many pixels differ strongly.
== "classroom.png" and "pbrt.png" are different
```

**Good enough** to close the issue ...

**Comment by wahn** [comment]
And this is how Rust renders the scene in about 7 hours (still using **uni-directional** path tracing):

![classroom_pbrt_rust](https://user-images.githubusercontent.com/1074865/34767647-8df8c426-f5f0-11e7-9935-d404d125d7f4.png)
